"""sec

Revision ID: aab69772040d
Revises: c016002d204a
Create Date: 2022-09-08 18:12:39.970420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab69772040d'
down_revision = 'c016002d204a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###
