"""sec

Revision ID: c016002d204a
Revises: aaed21fdf84b
Create Date: 2022-09-08 14:34:13.660514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c016002d204a'
down_revision = 'aaed21fdf84b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_group_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_group_id_fkey', 'posts', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
